### ISSUE TITLE
Schiff kann sich bewegen (Hintergrund scrollt/animiert)

### ISSUE THREAD

**Issue by ChrisThor** [codingHahn/UBootVonDerSeite#24]

**Comment by ChrisThor** [comment]
Solange der Motor läuft, schwimmt das Schiff horizontal mit konstanter Geschwindigkeit

**Comment by codingHahn** [comment]
Ich wäre dafür, dass sich das Schiff nicht bewegt. Es bewegt sich nur der Hintergrund

**Comment by KevinErath** [comment]
Ja, das Schiff soll immer in der Mitte sein, es bewegt sich nur der Hintergrund

**Comment by HenrikvonStalter** [comment]
Hintergrund bewegt sich.
