### ISSUE TITLE
Mit Objekten interagieren

### ISSUE THREAD

**Issue by KevinErath** [codingHahn/UBootVonDerSeite#46]

**Comment by kellerkindt** [comment]
Das Welt-Objekt muss von Area2D erben und im zugewiesenen Skript folgende Funktion implementieren:

```
func interact_with_player(player):
    pass
```

**Comment by codingHahn** [comment]
Es fehlt eigentlich nur noch die Leiterimplementierung. Die mahct @HenrikvonStalter gerade.
